# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award_and_scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(default='gold_medal', max_length=100)),
                ('catalog', models.TextField(max_length=5000)),
            ],
            options={
                'db_table': 'Award_and_scholarship',
            },
        ),
        migrations.CreateModel(
            name='Director_gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT')], default='INCOMPLETE', max_length=10)),
                ('correspondence_address', models.TextField(default='adress', max_length=40)),
                ('nearest_policestation', models.TextField(default='station', max_length=30)),
                ('nearest_railwaystation', models.TextField(default='station', max_length=30)),
                ('relevant_document', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student')),
            ],
            options={
                'db_table': 'Director_gold',
            },
        ),
        migrations.CreateModel(
            name='Director_silver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearest_policestation', models.TextField(default='station', max_length=30)),
                ('nearest_railwaystation', models.TextField(default='station', max_length=30)),
                ('correspondence_address', models.TextField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT')], default='INCOMPLETE', max_length=10)),
                ('relevant_document', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.Award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student')),
            ],
            options={
                'db_table': 'Director_silver',
            },
        ),
        migrations.CreateModel(
            name='Mcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother_name', models.CharField(max_length=30, null=True)),
                ('brother_occupation', models.TextField(max_length=100, null=True)),
                ('sister_name', models.CharField(max_length=30, null=True)),
                ('sister_occupation', models.TextField(max_length=100, null=True)),
                ('income_father', models.IntegerField(default=0)),
                ('income_mother', models.IntegerField(default=0)),
                ('income_other', models.IntegerField(default=0)),
                ('father_occ', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('public', 'Public'), ('business', 'Business'), ('medical', 'Medical'), ('consultant', 'Consultant'), ('pensioners', 'Pensioners')], default='Government', max_length=10)),
                ('mother_occ', models.CharField(choices=[('EMPLOYED', 'EMPLOYED'), ('HOUSE_WIFE', 'HOUSE_WIFE')], default='HOUSE-WIFE', max_length=10)),
                ('relevant_document', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT')], default='INCOMPLETE', max_length=10)),
                ('annual_income', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('award_id', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='scholarships.Award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcm_info', to='academic_information.Student')),
            ],
            options={
                'db_table': 'Mcm',
            },
        ),
        migrations.CreateModel(
            name='Notional_prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spi', models.FloatField()),
                ('cpi', models.FloatField()),
                ('year', models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4'), ('PG1', 'PG1'), ('PG2', 'PG2')], max_length=10)),
            ],
            options={
                'db_table': 'Notional_prize',
            },
        ),
        migrations.CreateModel(
            name='Previous_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2018)),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.Award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student')),
            ],
            options={
                'db_table': 'Previous_winner',
            },
        ),
        migrations.CreateModel(
            name='Proficiency_dm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_document', models.FileField(blank=True, null=True, upload_to='')),
                ('title_name', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT')], default='INOMPLETE', max_length=10)),
                ('nearest_policestation', models.TextField(default='station', max_length=30)),
                ('nearest_railwaystation', models.TextField(default='station', max_length=30)),
                ('correspondence_address', models.TextField(max_length=150, null=True)),
                ('no_of_students', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.Award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student')),
            ],
            options={
                'db_table': 'Proficiency_dm',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default=datetime.date.today)),
                ('enddate', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('time', models.CharField(choices=[('0', '12 Midnight'), ('1am', '1'), ('2am', '2'), ('3am', '3'), ('4am', '4'), ('5am', '5'), ('6am', '6'), ('7am', '7'), ('8am', '8'), ('9am', '9'), ('10am', '10'), ('11am', '11'), ('12 Noon', '12'), ('1pm', '13'), ('2pm', '14'), ('3pm', '15'), ('4pm', '16'), ('5pm', '17'), ('6pm', '18'), ('7pm', '19'), ('8pm', '20'), ('9pm', '21'), ('10pm', '22'), ('11pm', '23'), ('12 Midnight', '0')], max_length=10)),
                ('batch', models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4'), ('PG1', 'PG1'), ('PG2', 'PG2')], max_length=10)),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.Award_and_scholarship')),
            ],
            options={
                'db_table': 'Release',
            },
        ),
    ]
